server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
            - id: r1
              uri: http://unitauthback:8085
              predicates:
                - Path=/api/**,/auth/**
            - id: r2
              uri: http://unittestback:8083
              predicates:
                - Path=/unitTest/**
  reactor:
    netty:
      


